### ISSUE TITLE
mac  下 gitbook serve 出错

### ISSUE THREAD

**Issue by kakukeme** [zhangjikai/gitbook-use#3]
phantom stderr: child_process.js:380
    throw new TypeError('"file" argument must be a non-empty string');
    ^

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:380:11)
    at exports.spawn (child_process.js:487:38)
    at Object.<anonymous> (/Users/kokia/kokia_2017_iOS/gitbook-use/node_modules/phantomjs/bin/phantomjs:22:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)

$ node -v
v8.2.0

**Comment by zhangjikai** [comment]
不好意思啊，我没有 mac 电脑，没办法测试一下，你可以先试试什么插件都不加，然后运行一下，如果还是有问题，你可以去 [GitBook 的项目](https://github.com/GitbookIO/gitbook) 下提 issue
